apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      volumes: # Define volume
        - name: shared-volume
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: pong-app
          image: leevihalme/pong-app:latest
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-volume
              mountPath: /usr/src/app/files
