apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pong-app-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong-app
          image: leevihalme/pong-app:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5500"
            - name: DATABASE_URL
              value: "postgresql://postgres:lamepassword@postgres-svc:5432/pingpong"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /pong/healthz
              port: 5500
  strategy:
    canary:
      analysis:
        templates:
          - templateName: pong-cpu-rate
      steps:
        - setWeight: 20
        - pause: { duration: 5m }
