apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong-app
          image: leevihalme/pong-app:f788a07cd7ef7edacd0d911854b6acefb63b9a7c
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5500"
            - name: DATABASE_URL
              value: "postgresql://postgres:lamepassword@postgres-svc:5432/pingpong"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /pong/healthz
              port: 5500
  # strategy:
  #   canary:
  #     analysis:
  #       templates:
  #         - templateName: pong-cpu-rate
  #     steps:
  #       - setWeight: 20
  #       - pause: { duration: 5m }
