apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  # property-like keys; each key maps to a simple value
  message: "Hello from ConfigMap!"

  # file-like keys
  information: |
    This is a multi-line
    value stored in a ConfigMap.
    It can contain line breaks
    and other formatting.
