apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  # property-like keys; each key maps to a simple value
  message: "Hello from ConfigMap!"

  # file-like keys
  information: |
    This is a multi-line
    value stored in a ConfigMap.
    It can contain line breaks
    and other formatting.

  information_file_path: "/config/information.txt"
  output_file_path: "files/output.txt"

  pong_api_endpoint: "http://pong-app-svc:5500/pings"
