apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-volume
          persistentVolumeClaim:
            claimName: example-claim
        - name: config
          configMap:
            name: log-output-config
            items:
              - key: information
                path: information.txt
      containers:
        - name: log-output-writer
          image: leevihalme/log-output:writer # use writer tag for the standalone container
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: OUTPUT_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: output_file_path
        - name: log-output-server
          image: leevihalme/log-output:server # use server tag for the HTTP container
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-volume
              mountPath: /usr/src/app/files
            - name: config
              mountPath: /config
              readOnly: true
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: message
            - name: INFORMATION_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: information_file_path
            - name: OUTPUT_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: output_file_path
            - name: PONG_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: pong_api_endpoint
              # static value provided directly
            - name: PORT
              value: "5000"
