apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: log-output-ingress-route
  namespace: exercises
spec:
  parentRefs:
    - name: log-gateway
      namespace: istio-system
  rules:
    # Log Output Rules
    - matches:
        - path: { type: PathPrefix, value: /get-log }
        - path: { type: PathPrefix, value: /log/healthz }
      backendRefs:
        - name: log-output-svc
          port: 5000

    # Pong App Rules
    - matches:
        - path: { type: PathPrefix, value: /pingpong }
        - path: { type: PathPrefix, value: /pings }
        - path: { type: PathPrefix, value: /pong/healthz }
      backendRefs:
        - name: pong-app-svc
          port: 5500
