apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
spec:
  rules:
    - http:
        paths:
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 5000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: pong-app-svc
                port:
                  number: 5500
