apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: exercises
spec:
  rules:
    - http:
        paths:
          - path: /get-log
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 5000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: pong-app-svc
                port:
                  number: 5500
          - path: /pings
            pathType: Prefix
            backend:
              service:
                name: pong-app-svc
                port:
                  number: 5500
