apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 5000 # The port the service exposes to the cluster
      targetPort: 5000 # The port on the container itself
