apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes: # Define volume
        - name: shared-volume
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: todo-app
          image: leevihalme/todo-app:latest
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-volume
              mountPath: /usr/src/app/static
