apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller-sa
      containers:
        - name: controller
          image: leevihalme/dummysite-controller:latest
          imagePullPolicy: Always
