apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller-sa
  namespace: exercises
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller-role
rules:
  # 1. Permissions for your Custom Resource
  - apiGroups: ["stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch"]
  # 2. Permissions to create the "copy" resources
  - apiGroups: ["apps", ""]
    resources: ["deployments", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller-binding
subjects:
  - kind: ServiceAccount
    name: dummysite-controller-sa
    namespace: exercises
roleRef:
  kind: ClusterRole
  name: dummysite-controller-role
  apiGroup: rbac.authorization.k8s.io
