apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-postgres-pv # Unique Name
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/tmp/todo-postgres-data" # Unique Folder
    type: DirectoryOrCreate
