apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend # This is the app as declared in the deployment.
  ports:
    - name: http
      protocol: TCP
      port: 8000 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 8000 # This is the target port
