name: Build and publish todo-backend

on:
  push:
    paths:
      # Only trigger if files in this folder change
      - "todo-backend/**"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish
        run: |-
          # Build from the specific subdirectory
          docker build -t "leevihalme/todo-backend:$GITHUB_SHA" ./todo-backend
          docker push "leevihalme/todo-backend:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image using Kustomize
        # This part will do nothing as the cluster is running locally,
        # but in a real scenario, we would update the image tag here
        run: |
          cd todo-backend
          echo "kustomize edit set image PROJECT/IMAGE=leevihalme/todo-backend:$GITHUB_SHA"

      - name: Commit change
        uses: EndBug/add-and-commit@v9
        with:
          add: "todo-backend/kustomization.yml"
          message: "New version released: ${{ github.sha }}"
